FROM golang:1.22-alpine AS builder
WORKDIR /workspace
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /manager ./controller

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /manager /manager
USER 65532
ENTRYPOINT ["/manager"]
