//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcess) DeepCopyInto(out *DeviceProcess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcess.
func (in *DeviceProcess) DeepCopy() *DeviceProcess {
	if in == nil {
		return nil
	}
	out := new(DeviceProcess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceProcess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessArtifact) DeepCopyInto(out *DeviceProcessArtifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessArtifact.
func (in *DeviceProcessArtifact) DeepCopy() *DeviceProcessArtifact {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessDeployment) DeepCopyInto(out *DeviceProcessDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessDeployment.
func (in *DeviceProcessDeployment) DeepCopy() *DeviceProcessDeployment {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceProcessDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessDeploymentList) DeepCopyInto(out *DeviceProcessDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeviceProcessDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessDeploymentList.
func (in *DeviceProcessDeploymentList) DeepCopy() *DeviceProcessDeploymentList {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceProcessDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessDeploymentSpec) DeepCopyInto(out *DeviceProcessDeploymentSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.UpdateStrategy.DeepCopyInto(&out.UpdateStrategy)
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessDeploymentSpec.
func (in *DeviceProcessDeploymentSpec) DeepCopy() *DeviceProcessDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessDeploymentStatus) DeepCopyInto(out *DeviceProcessDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessDeploymentStatus.
func (in *DeviceProcessDeploymentStatus) DeepCopy() *DeviceProcessDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessDeploymentStrategy) DeepCopyInto(out *DeviceProcessDeploymentStrategy) {
	*out = *in
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(DeviceProcessRollingUpdate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessDeploymentStrategy.
func (in *DeviceProcessDeploymentStrategy) DeepCopy() *DeviceProcessDeploymentStrategy {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessDeploymentStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessEnvVar) DeepCopyInto(out *DeviceProcessEnvVar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessEnvVar.
func (in *DeviceProcessEnvVar) DeepCopy() *DeviceProcessEnvVar {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessEnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessExecAction) DeepCopyInto(out *DeviceProcessExecAction) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessExecAction.
func (in *DeviceProcessExecAction) DeepCopy() *DeviceProcessExecAction {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessExecAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessExecution) DeepCopyInto(out *DeviceProcessExecution) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]DeviceProcessEnvVar, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessExecution.
func (in *DeviceProcessExecution) DeepCopy() *DeviceProcessExecution {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessHealthCheck) DeepCopyInto(out *DeviceProcessHealthCheck) {
	*out = *in
	in.Exec.DeepCopyInto(&out.Exec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessHealthCheck.
func (in *DeviceProcessHealthCheck) DeepCopy() *DeviceProcessHealthCheck {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessList) DeepCopyInto(out *DeviceProcessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeviceProcess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessList.
func (in *DeviceProcessList) DeepCopy() *DeviceProcessList {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceProcessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessRollingUpdate) DeepCopyInto(out *DeviceProcessRollingUpdate) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessRollingUpdate.
func (in *DeviceProcessRollingUpdate) DeepCopy() *DeviceProcessRollingUpdate {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessRollingUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessSpec) DeepCopyInto(out *DeviceProcessSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	out.Artifact = in.Artifact
	in.Execution.DeepCopyInto(&out.Execution)
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(DeviceProcessHealthCheck)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessSpec.
func (in *DeviceProcessSpec) DeepCopy() *DeviceProcessSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessStatus) DeepCopyInto(out *DeviceProcessStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessStatus.
func (in *DeviceProcessStatus) DeepCopy() *DeviceProcessStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessTemplate) DeepCopyInto(out *DeviceProcessTemplate) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessTemplate.
func (in *DeviceProcessTemplate) DeepCopy() *DeviceProcessTemplate {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessTemplateMetadata) DeepCopyInto(out *DeviceProcessTemplateMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessTemplateMetadata.
func (in *DeviceProcessTemplateMetadata) DeepCopy() *DeviceProcessTemplateMetadata {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessTemplateMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceProcessTemplateSpec) DeepCopyInto(out *DeviceProcessTemplateSpec) {
	*out = *in
	out.Artifact = in.Artifact
	in.Execution.DeepCopyInto(&out.Execution)
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(DeviceProcessHealthCheck)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceProcessTemplateSpec.
func (in *DeviceProcessTemplateSpec) DeepCopy() *DeviceProcessTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceProcessTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceRef) DeepCopyInto(out *DeviceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceRef.
func (in *DeviceRef) DeepCopy() *DeviceRef {
	if in == nil {
		return nil
	}
	out := new(DeviceRef)
	in.DeepCopyInto(out)
	return out
}
